/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.capgemini;

import org.junit.*;

public class UserRegistrationTest {
	
	@Test
    public void givenFirstName_WhenValid_ReturnTrue() {
        UserRegistration user = new UserRegistration();
        try {
        Assert.assertTrue(user.fname.valid("Kashif"));
        }catch(UserRegistrationException e) {
        	Assert.assertEquals("Please enter proper firstname", e.getMessage());
        }
    }
 @Test
    public void givenFirstName_WhenInvalid_ReturnFalse() {
        UserRegistration user = new UserRegistration();
        try {
        Assert.assertFalse(user.fname.valid("kashif"));
        }catch(UserRegistrationException e) {
        	Assert.assertEquals("Please enter proper firstname", e.getMessage());
        }
    }
 @Test
    public void givenLastName_WhenValid_ReturnTrue() {
        UserRegistration user = new UserRegistration();
        try {
        Assert.assertTrue(user.lname.valid("Ansari"));
        }catch(UserRegistrationException e) {
        	Assert.assertEquals("Please enter proper lastname", e.getMessage());
        }
    }
 @Test
    public void givenLastName_WhenInvalid_ReturnFalse() {
        UserRegistration user = new UserRegistration();
        try {
        Assert.assertFalse(user.lname.valid("ansari"));
        }catch(UserRegistrationException e) {
        	Assert.assertEquals("Please enter proper lastname", e.getMessage());
        }
    }
 @Test
    public void givenEmail_WhenValid_ReturnTruee() {
        UserRegistration user = new UserRegistration();
        try {
        Assert.assertTrue(user.email.valid("abc@gmail.com"));
        }catch(UserRegistrationException e) {
        	Assert.assertEquals("Please enter proper email", e.getMessage());
        }
    }
 @Test
    public void givenEmail_WhenInvalid_ReturnFalse() {
        UserRegistration user = new UserRegistration();
        try {
        Assert.assertFalse(user.email.valid("kashif"));
        }catch(UserRegistrationException e) {
        	Assert.assertEquals("Please enter proper email", e.getMessage());
        }
    } 
 @Test
    public void givenMobileNo_WhenValid_ReturnTrue() {
        UserRegistration user = new UserRegistration();
        try {
        Assert.assertTrue(user.mobile.valid("91 8737933455"));
        }catch(UserRegistrationException e) {
        	Assert.assertEquals("Please enter proper mobile no.", e.getMessage());
        }
    }
 @Test
    public void givenMobileNo_WhenInvalid_ReturnFalse() {
        UserRegistration user = new UserRegistration();
        try {
        Assert.assertFalse(user.mobile.valid("12345"));
        }catch(UserRegistrationException e) {
        	Assert.assertEquals("Please enter proper mobile no.", e.getMessage());
        }
    }
 @Test
    public void givenPassword_WhenValid_ReturnTrue() {
        UserRegistration user = new UserRegistration();
        try {
        Assert.assertTrue(user.pwd.valid("Kashif1@"));
        }catch(UserRegistrationException e) {
        	Assert.assertEquals("Please enter proper password", e.getMessage());
        }
    }
 @Test
    public void givenPassword_WhenInvalid_ReturnFalse() {
        UserRegistration user = new UserRegistration();
        try {
        Assert.assertFalse(user.pwd.valid("kas"));
        }catch(UserRegistrationException e) {
        	Assert.assertEquals("Please enter proper password", e.getMessage());
        }
    }
}
