/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.capgemini;

import java.util.regex.*;

interface IValidator {
	boolean valid(String string) throws UserRegistrationException;
}
public class UserRegistration {
	IValidator fname = n -> {
		return Pattern.compile("^[A-Z][a-zA-Z]{2,}$").matcher(n).find();
	};
	
	IValidator lname = n -> {
		return Pattern.compile("^[A-Z][a-zA-Z]{2,}$").matcher(n).find();
	};
	
	IValidator mobile = n -> {
		return Pattern.compile("^[0-9]{2}[ ][1-9][0-9]{9}$").matcher(n).find();
	};
	
	IValidator email = n -> {
		return Pattern.compile("^abc+([_+-.]{0,1}([a-zA-Z0-9]+))*[@][a-z0-9]{1,}[.]([c][o][m]|[n][e][t])([.][a-zA-Z]{2,}){0,1}$").matcher(n).find();
	};
	
	IValidator pwd = n -> {
		return Pattern.compile("(?=.*[A-Z])(?=.*\\d)(?=.*\\W)(?!.*\\W\\w*\\W)(?!.*\\s).{5,}$").matcher(n).find();
	};
	public static void main(String[] args) {
		System.out.println("Welcome to User Registration.");
	}
}