/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.capgemini;

import java.util.*;
import java.util.regex.*;

public class UserRegistration {
	Scanner sc=new Scanner(System.in);
	public boolean fname(String first) throws UserRegistrationException {
		//System.out.println("Enter your first name (NOTE: First letter should be capital and shuold have minimum 3 characters) :");
        //String first = sc.next();
		Pattern p = Pattern.compile("^[A-Z][a-zA-Z]{2,}$");
		Matcher m = p.matcher(first);
		Boolean check = m.find();
        /*if(check) {
        	System.out.println("Valid first name.");
        }
        else
        	System.out.println("ERROR ! Requirement not satisfied.");
        return check;*/
		if(!check)
			throw new UserRegistrationException ("Please enter proper firstname");
		return check;
	}
	public boolean lname(String last) throws UserRegistrationException {
		//System.out.println("Enter your last name (NOTE: First letter should be capital and shuold have minimum 3 characters) :");
        //String first = sc.next();
		Pattern p = Pattern.compile("^[A-Z][a-zA-Z]{2,}$");
		Matcher m = p.matcher(last);
		Boolean check = m.find();
        /*if(check) {
        	System.out.println("Valid last name.");
        }
        else
        	System.out.println("ERROR ! Requirement not satisfied.");
        return check;*/
        if(!check)
			throw new UserRegistrationException ("Please enter proper lastname");
		return check;
	}
	public boolean email(String email) throws UserRegistrationException {
		//System.out.println("Enter your Email:");
        //String email = sc.next();
		Pattern p = Pattern.compile("^abc+([_+-.]{0,1}([a-zA-Z0-9]+))*[@][a-z0-9]{1,}[.]([c][o][m]|[n][e][t])([.][a-zA-Z]{2,}){0,1}$");
		Matcher m = p.matcher(email);
		Boolean check = m.find();
		/*if(check) {
        	System.out.println("Valid Email.");
        }
        else
        	System.out.println("ERROR ! Requirement not satisfied.");
		return check;*/
		if(!check)
			throw new UserRegistrationException ("Please enter proper email");
		return check;
	}
	public boolean mobile(String mobile) throws UserRegistrationException {
		//Scanner in=new Scanner(System.in);
		//System.out.println("Enter your Mobile No:");
		//String mobile = in.nextLine();
		Pattern p = Pattern.compile("^[0-9]{2}[ ][1-9][0-9]{9}$");
		Matcher m = p.matcher(mobile);
		Boolean check = m.find();
		/*if(check) {
        	System.out.println("Valid Mobile Number.");
        }
        else
        	System.out.println("ERROR ! Requirement not satisfied.");
		return check;*/
		if(!check)
			throw new UserRegistrationException ("Please enter proper mobile no.");
		return check;
	}
	public boolean pwd(String pwd) throws UserRegistrationException {
		//System.out.println("Enter your Password:");
		//String pwd = sc.next();
		Pattern p = Pattern.compile("(?=.*[A-Z])(?=.*\\d)(?=.*\\W)(?!.*\\W\\w*\\W)(?!.*\\s).{5,}$");
		Matcher m = p.matcher(pwd);
		Boolean check = m.find();
		/*if(check) {
        	System.out.println("Valid Password.");
        }
        else
        	System.out.println("ERROR ! Requirement not satisfied.");
		return check;*/
		if(!check)
			throw new UserRegistrationException ("Please enter proper password");
		return check;
	}/*
	public String analyseMood(String message) {
		if (message.contains("Happy"))
			return "Happy";
		else
			return "SAD";
	}*/
	public static void main(String[] args) {
		System.out.println("Welcome to User Registration.");
	/*	UserRegistration u = new UserRegistration();
		u.fname();
		u.lname();
		u.email();
		u.mobile();
		u.pwd(); */
	}
}